module.exports = {
  'extends': ['eslint:recommended'],
  'env': {
    'node': true,
    'browser': true,
    'es6': true,
  },
  'rules': {
    'no-console': 0,
    'no-shadow': 2,
    'jsx-quotes': 1,
    'semi': [1, 'never'],
    'comma-dangle': [1, 'always-multiline'],
    'array-bracket-spacing': [1, 'never'],
    'block-spacing': [1, 'always'],
    'computed-property-spacing': 1,
    'eol-last': 1,
    'indent': [1, 2],
    'keyword-spacing': 1,
    'no-spaced-func': 1,
    'no-trailing-spaces': 1,
    'no-whitespace-before-property': 1,
    'quotes': [1, 'single', {'avoidEscape': true, 'allowTemplateLiterals': true}],
    'object-curly-spacing': [1, 'never'],
    'space-before-blocks': [1, 'always'],
    'space-before-function-paren': [1, 'never'],
    'space-in-parens': [1, 'never'],
    'space-infix-ops': 1,
    'space-unary-ops': 1,
    'spaced-comment': 1,
    'arrow-spacing': 1,
    'generator-star-spacing': 1,
    'template-curly-spacing': [1, 'never'],
    'yield-star-spacing': 1,
    'no-multi-spaces': 1,
  },
}
